### ISSUE TITLE
Error: msgflo-send-message while executing this command

### ISSUE THREAD

**Issue by mohandass-pat** [msgflo/msgflo#180]
Hi. I just followed the docs(https://msgflo.org/docs/usage/index.html) to setup msgFlo. But I'm getting the below error. i'm using mqtt. 

```
$ msgflo-send-message --queue repeater.IN --json '{ "foo": "bar" }'
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../bin/utils/send'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/pat-003/Documents/graph-playground/test-run/node_modules/msgflo/bin/msgflo-send-message:2:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

```

Help me to solve this issue. Thanks in advance :)

**Comment by jonnor** [comment]
What node.js version? Are you using a special node.js loader (I see some cjs references)?

**Comment by mohandass-pat** [comment]
Hi. Thanks for the reply. I'm using Node v10.15.2, npm 6.9.0. I'm not using any special loader

**Comment by mohandass-pat** [comment]
In npm module, msgflo/bin/mesgflo-send is referring wrong path. 

In msgflo-send file, 
`require('../bin/utils/send').main()
`
need to be replaced with 

`require('../lib/utils/send').main()
`

**Comment by jonnor** [comment]
Ouch, that is a bug. Reopening.
